services:
  # Nodeアプリケーションのサービス設定
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=valerosso_user
      - DB_PASSWORD=valerosso_password
      - DB_NAME=valerosso
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    # migrationのみ実行（seedersは不使用）
    command: >
      sh -c "npx sequelize-cli db:migrate && node server.js"
  
  # MySQLデータベースのサービス設定
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=valerosso
      - MYSQL_USER=valerosso_user
      - MYSQL_PASSWORD=valerosso_password
      - TZ=Asia/Tokyo
    command: --default-time-zone='+09:00'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: